### ISSUE TITLE
Tests are not generated for new methods

### ISSUE THREAD

**Issue by Boulty** [SquaretestLLC/Squaretest#1]
Initially, tests for methods are added (any look very good). However, if a new method is added to the class under test then the _Squaretest | Generate Test_ command just switches to the test class but does not genetate a new test as expected.

**Comment by nate-dev** [comment]
Thank you for the feedback! 
Unfortunately adding new tests to an existing test-class via the Generate Test Action is not currently supported and would be difficult to implement reliably in the current version of Squaretest. 

I am considering a couple of solutions to help users auto-generate new tests in an existing test-class, though, as this is a fairly common usecase.

**Comment by nate-dev** [comment]
Hi! I just wanted to let you know I released an update to Squaretest that allows you to add test-methods to existing test-classes! Please see the update demo video on [squaretest.com](https://squaretest.com) for details.
