### ISSUE TITLE
String in Method UUId.fromString does not have quotation marks

### ISSUE THREAD

**Issue by arnzel** [SquaretestLLC/Squaretest#10]
Plugin generates lines like this

final UUID parameter =  UUID.fromString(3fd7b159-a244-4a93-ab72-36d1eb730054);

which does not compile

**Comment by nate-dev** [comment]
Thanks for the feedback! This will be fixed in the next update.

**Comment by nate-dev** [comment]
This is fixed in the latest update (1.3.2).
