### ISSUE TITLE
Generated test constructor call requires manual insertion of (short) before the short values

### ISSUE THREAD

**Issue by larrytalley** [SquaretestLLC/Squaretest#11]
I have a class with a couple of "Short" variables that was generated by Hibernate. I want Squaretest to generate a test class that will break if Hibernate ever generates the subject class differently. I generate a test class but it calls a constructor with literals, and, for the "Short" variable, it doesn't cast the literal, and the test class won't compile.

Example:
public class Bob {
     private Short year;
}
I generate test:
public class BobTest {

    private Bob bobUnderTest;

    @Before
    public void setUp() {
        bobUnderTest = new Bob(0);
    }
}

--- I'd like it to generate 
public class BobTest {

    private Bob bobUnderTest;

    @Before
    public void setUp() {
        bobUnderTest = new Bob((short)0);
    }
}

**Comment by nate-dev** [comment]
Thanks for the feedback!
This is definitely a bug.

**Comment by nate-dev** [comment]
This is fixed in the 1.4 update (released 11/11/2019).
