### ISSUE TITLE
Nested Classes

### ISSUE THREAD

**Issue by Techtony96** [SquaretestLLC/Squaretest#12]
Hello,

How can I modify the template in order to generate tests of my public static nested classes? I have looked at the template API page, but am not able to find any way to even see if these classes exist.

Thanks

**Comment by nate-dev** [comment]
Thanks for the feedback. 

The template API doesn't have a way to access information about inner classes at this time.
This is something I'd like to support eventually, as static inner classes are commonly used in the Builder pattern. I can't promise anything in the near future, though.

**Comment by Techtony96** [comment]
Ok, thank you for the information!
