### ISSUE TITLE
Generated tests contains not existing imports

### ISSUE THREAD

**Issue by arnzel** [SquaretestLLC/Squaretest#14]
When creating tests with mockito squaretes generates the following imports

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;

But this classes do not exist in my project. I had to correct them to

import static org.mockito.Mockito.any;
import static org.mockito.Mockito.eq;

Not a big deal but it would be nice if plugin could detect mockito version from pom.xml or you could config mockito version somewhere so right imports are generated

**Comment by nate-dev** [comment]
Thanks for the feedback!
I updated the default templates in Squaretest 1.4 (released on 11/11/2019) to import the correct matchers based on which classes are available on the test classpath. 

If you're using one of the default templates included with Squaretest, you only need to install the latest update.

If you're using a custom template, you'll need to make the following changes:

1. Replace the following import statements:
```
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
```
with:
`#renderImportsForMatchers()`

2. Define the renderImportsForMatchers() macro at the bottom of the file:
```
#macro(renderImportsForMatchers)
    #set($macro.matcherCanonicalName = 'org.mockito.ArgumentMatchers')
    #if((!$ClassUtils.isInTestClasspath($macro.matcherCanonicalName))
        && $ClassUtils.isInTestClasspath('org.mockito.Matchers'))
        #set($macro.matcherCanonicalName = 'org.mockito.Matchers')
    #end
    import static ${macro.matcherCanonicalName}.any;
    import static ${macro.matcherCanonicalName}.anyInt;
    import static ${macro.matcherCanonicalName}.anyString;
    import static ${macro.matcherCanonicalName}.eq;
#end
```
