### ISSUE TITLE
Cant login to Forum with Gmail or Facebook

### ISSUE THREAD

**Issue by arnzel** [SquaretestLLC/Squaretest#15]
Cant login here https://squaretest.com/#forum

Facebook error code

Login Failed: You can't use Facebook to log into this app or website because there's an issue with its implementation of Facebook Login.

**Comment by nate-dev** [comment]
Thank you for reporting this!

**Comment by nate-dev** [comment]
I deprecated the old Squaretest forum and switched to [GitHub Discussions](https://github.com/SquaretestLLC/Squaretest/discussions).
