### ISSUE TITLE
Support for Mockmvc

### ISSUE THREAD

**Issue by arnzel** [SquaretestLLC/Squaretest#17]
I think a nice feature would be to use Mockmvc for Classes which are Annotated with @Controller or @RestController.

So for examplke for a given Controller

`
@RestController
public class MyController ...

  @GetMapping("/path/{pathParameter}/")
  public ResponseEntity<Object> path(@RequestParam String requestParameter)..
   
 

`

generate something like

`
mockMvc = MockMvcBuilders.standaloneSetup(myController).build();
...
    String url = format("/path/%s/",pathParameter);
    MvcResult mvcResult = mockMvc
        .perform(MockMvcRequestBuilders
            .get(url).param("requestParameter",requestParameter)
            .accept(MediaType.APPLICATION_JSON))
        .andDo(print())
`

**Comment by nate-dev** [comment]
Thank you for the feedback!
Squaretest 1.5.5 includes templates for JUnit + Spring + AssertJ. These templates generate special, MockMvc tests for Spring Controllers. For other classes, the templates generate the same code as the standard JUnit + Mockito templates.
