### ISSUE TITLE
Support Scala as test language.

### ISSUE THREAD

**Issue by He-Pin** [SquaretestLLC/Squaretest#2]
Currently, it only supports java and groovy.

**Comment by nate-dev** [comment]
Thanks for the feedback. I like the idea of supporting Scala. Unfortunately, I can’t make any promises around implementing it in the near future, though, as this would require a fairly large change to Squaretest.

**Comment by hepin1989** [comment]
Yes, thank you for bringing Squaretest to us.

**Comment by nate-dev** [comment]
Squaretest will not be able to support Scala.
