### ISSUE TITLE
Can we use NoArgsConstructor and use getters and setters instead of AllArgsConstructor?

### ISSUE THREAD

**Issue by mehtakaran9** [SquaretestLLC/Squaretest#20]
Whenever the squaretest plugin creates a new test class, it uses All argument constructors instead of no-args constructors. 
The issue with this is that whenever a POJO's elements are changed, the test cases give an error for all the constructors used in all the test cases. This can be avoided with No arg constructor and using getters and setters additionally to set the values of the elements of the POJO classes.

**Comment by nate-dev** [comment]
Thank you for the feedback. I apologize for the delayed response. Currently there is not a good way to implement this. I will consider this as a possible future enhancement to Squaretest, but I can't commit to implementing it at this time.

**Comment by nate-dev** [comment]
I added a setting called "Data Constructor Limit" to the Squaretest settings menu. If the nested constructor call for a recognized data class is greater than this limit, Squaretest will use the no-args constructor + setter methods to initialize the data class instead. This setting currently only applies to recognized data classes, meaning classes with annotations from lombok, Jackson, Gson, DynamoDB, etc. 

To use the no-args constructor for recognized data classes, please go to File | Settings | Squaretest, and change this setting from 5 to 0.
