### ISSUE TITLE
mocks use invalid values to initialize joda DateTime object 

### ISSUE THREAD

**Issue by arnzel** [SquaretestLLC/Squaretest#21]
I get the following invocation for a method which uses joda DateTime Object

when(myMock.getSomething(new DateTime(0, 0, 0, 0, 0, 0, 0))).thenReturn(0);

which leads to error

org.joda.time.IllegalFieldValueException: Value 0 for monthOfYear must be in the range [1,12]

**Comment by nate-dev** [comment]
Thank you for the feedback. This issue should be fixed now.
