### ISSUE TITLE
Add new Default Template: Junit 5 + Mockito + AssertJ

### ISSUE THREAD

**Issue by diego-alcantara-nemo** [SquaretestLLC/Squaretest#4]
It  would be useful to have a new default template, or to be able to choose which assertion library is preferred, in my case AssertJ

In case the choice is for a new default template to be added, the frameworks/librarys would be: Junit 5 + Mockito + AssertJ, I'm attaching the corresponding Velocity Template

[Juni5_Mockito_AssertJ.txt](https://github.com/SquaretestLLC/Squaretest/files/2910439/Juni5_Mockito_AssertJ.txt)

**Comment by nate-dev** [comment]
Thanks for the feedback!

I like the idea of making it easier for users to create Squaretest templates that use AssertJ.
I'm still deciding on the best approach to implement this, though.

In the mean time, I will update Squaretest to support adding test-methods to existing test-classes that use AssertJ, though. Currently, when creating test-methods, Squaretest uses assertions from either JUnit4 or JUnit5, depending on which framework is used in the test-class.

**Comment by mqqx** [comment]
I have the same use case with JUnit 5 + Mockito 3 + AssertJ 3, are there any updates to this or the usage of AssertJ?

**Comment by nate-dev** [comment]
Thank you for the feedback. As of update 1.5.4 (released today), Squaretest includes templates for JUnit4 + Mockito + AssertJ and JUnit5 + Mockito + AssertJ.

**Comment by mqqx** [comment]
Thanks I just bought it. :)
