### ISSUE TITLE
Method annotation

### ISSUE THREAD

**Issue by Fujiwaranosai** [SquaretestLLC/Squaretest#8]
Is it possible to get annotations of a method?

**Comment by nate-dev** [comment]
Thanks for the feedback. Sorry for the delayed response.

There currently isn't a way to get the list of annotations on a method. I haven't decided how to put annotations into the template data model yet.

I will create the following APIs, though:

Method.isAnnotatedWith(String... annotationNames);
Constructor.isAnnotatedWith(String... annotationNames);

SourceClass.methodsAnnotatedWith(String... annotationNames)
SourceClass.constructorsAnnotatedWith(String... annotationNames)

These will be similar to the other APIs in the data model; e.g.  SourceClass.fieldsAnnotatedWith(String... annotationNames) and ClassMember.isAnnotatedWith(String... annotationNames).

The annotationNames parameters can be canonical names or simple names.

**Comment by nate-dev** [comment]
The latest Squaretest update (1.3.2) has the methods mentioned above. I also updated the documentation on [squaretest.com/#template_api](https://squaretest.com/#template_api).
